name: Build and push to build branch.

on:
    push:
        branches: [trunk]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

            - name: Install NodeJS
              uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # v3.3.0
              with:
                  node-version-file: '.nvmrc'
                  cache: yarn

            - name: Install all dependencies
              run: |
                  composer install --no-dev
                  npm install

            - name: Build
              run: npm run build

            - name: Ignore .gitignore
              run: |
                  git add mu-plugins/blocks/*/build/* --force
                  git add vendor --force

            - name: Commit and push
              # Using a specific hash here instead of a tagged version, for risk mitigation, since this action modifies our repo.
              uses: actions-js/push@a52398fac807b0c1e5f1492c969b477c8560a0ba # 1.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: build
                  force: true
                  message: 'Build: ${{ github.sha }}'
