name: Static Analysis (Linting)

# Runs on any PR, and is also called by build.yml (on trunk) so the build branch
# is only updated after linting succeeds.
on:
    pull_request:
    workflow_call:

jobs:
    check:
        name: Lint everything

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

            - name: Install NodeJS
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - name: Install dependencies & setup configs
              run: |
                  npm ci
                  composer install
                  TEXTDOMAIN=wporg composer exec update-configs

            - name: Lint JavaScript and Styles
              run: |
                  npm run lint:css
                  npm run lint:js

